#!/usr/bin/php
<?php
require_once('path.inc');
require_once('get_host_info.inc');
require_once('rabbitMQLib.inc');

$client = new rabbitMQClient("testRabbitMQ.ini","speak");
if (isset($argv[1]))
{
  $msg = $argv[1];
}
else
{
  $msg = "test message";
}

$request = array();
$request['type'] = "Login"; //change hard coded variables to text box inputs (username/password)
$username = $_POST['username'];
$password= $_POST['password'];
$request['username'] = $username;
$request['password'] = $password;
$request['message'] = $msg;
$response = $client->send_request($request);
//$response = $client->publish($request);

echo "client received response: ".PHP_EOL;
print_r($response);
//see if you can grab the responce array
$returnCode = $response["returnCode"];
//echo $returnCode;
switch($returnCode){
	case 1:
		$sessionId = $response["sessionId"];
		echo "<script>
		sessionStorage.setItem('id',", $sessionId, ");
        	let info = sessionStorage.getItem(id);
        	</script>";
		
		break;
	default:
		echo "something went wrong";
		
	case 2:
		$usernmae = $response["username"];
		$password = $response["password"];
		echo"<script>
		sessionStorage.setItem('col',", $username, ");
		sessionStorage.setItem('ro',", $password, ");
		let user = sessionStorage.getItem(col);
		let pass = sessionStorage.getItem(ro);
		</script>";
			break;
	default:
		echo"wrong ones";
}
echo "\n\n";

echo $argv[0]." END".PHP_EOL;
?>
